import pygame

WINDOW_TITLE = "Pi Pokemon Game"

# Timing
TARGET_FPS = 30

# Resolution
LOGICAL_WIDTH = 240
LOGICAL_HEIGHT = 160

GAME_SCALE = 4

GAME_WIDTH = LOGICAL_WIDTH * GAME_SCALE
GAME_HEIGHT = LOGICAL_HEIGHT * GAME_SCALE

# Tiles
LOGICAL_TILE_SIZE = 16
GAME_TILE_SIZE = LOGICAL_TILE_SIZE * GAME_SCALE

# States
STATE_TEAM_BUILDER = "team_builder"
STATE_BATTLE = "battle"

DISPLAY_BORDER_COLOR = (40, 40, 40)
DISPLAY_BORDER_WIDTH = 2

KEY_TEAM_BUILDER = pygame.K_t
KEY_BATTLE = pygame.K_b
KEY_QUIT = pygame.K_q

COLOR_BLACK = (0, 0, 0)